/**
 * RS.lessons.CONTENIDO — lesson data as a plain JS array (no JSON, no fetch:
 * the app is opened over file:// and fetch() would be CORS-blocked).
 *
 * Each record follows the mandatory 13-section structure from
 * data/Modulo_Aprendizaje.odt section 15 ("Formato de salida para generar
 * una lección"): objetivo, concepto, ejemplo, bloques, comoFunciona, prueba,
 * modificacion, desafio, criterioTexto, pista, competencias, resultados,
 * nivel.
 *
 * `criterio` is null only for lessons with no run-derived success check.
 * Every lesson (1-8) now has a real, run-checkable `criterio` — Lesson 1's
 * identification-focused text is paired with a pre-loaded program (see
 * main.js's irALeccion) so it still has a goal to run toward. Lesson 2's
 * `criterio.evaluar(snapshot)` checks `dentroDeMeta(...)` (see check.js for
 * the snapshot shape).
 *
 * Lesson order follows data/Simulador.txt: 1 Bloques, 2 Secuencia, 3 Secuencia
 * II, 4 Variables, 5 Iteración, 6 Condición y sensores, 7 Condición II,
 * 8 Integración. Which blocks each lesson unlocks lives in
 * RS.toolbox.DESBLOQUEOS_POR_LECCION (src/blocks/toolbox.js). A lesson's
 * `criterio` may also expose an optional
 * `describir(snapshot, ok)` hook for lesson-specific behavioral feedback
 * text (see check.js).
 */
(function (global) {
  'use strict';

  var RS = global.RS = global.RS || {};
  RS.lessons = RS.lessons || {};

  // Shared field order for full-lesson rendering (home.js's current-lesson
  // screen and panel.js's in-workspace side panel both read from here, so
  // the two stay in sync).
  RS.lessons.SECCIONES = [
    { clave: 'objetivo', titulo: 'Objetivo' },
    { clave: 'concepto', titulo: 'Concepto' },
    { clave: 'ejemplo', titulo: 'Ejemplo' },
    { clave: 'bloques', titulo: 'Bloques utilizados' },
    { clave: 'comoFunciona', titulo: '¿Cómo funciona?' },
    { clave: 'prueba', titulo: 'Prueba en el simulador' },
    { clave: 'modificacion', titulo: 'Modificación' },
    { clave: 'desafio', titulo: 'Desafío' },
    { clave: 'criterioTexto', titulo: 'Criterio de éxito' },
    { clave: 'pista', titulo: 'Pista' },
    { clave: 'competencias', titulo: 'Competencias' },
    { clave: 'resultados', titulo: 'Resultados de aprendizaje' },
    { clave: 'nivel', titulo: 'Nivel de dificultad' }
  ];

  // v3 (cell-grid redesign): every lesson map is now authored as a grid
  // spec (`{col,row,colSpan,rowSpan}` regions, per design D1/D2) and
  // converted to the pixel shape `world.cargarMapa` already accepts via
  // `RS.gridAdapter.aPixeles(...)` — zero changes required in `world.js`,
  // `robot.js`, `sensors.js` or `check.js` (design D6). `CELL_SIZE=40`,
  // `GRID_COLS=20`, `GRID_ROWS=15` (src/config.js). Start cells (cell CENTER,
  // design D2): lessons 1-4 and 6 start at `{col:1,row:7}` = pixel `(60,300)`,
  // lesson 5 at `{col:1,row:3}` = `(60,140)`, lesson 7 at `{col:2,row:2}` =
  // `(100,100)`. Every `Delay(ms)` value after `avanzar` in the lesson text is derived from
  // the map geometry as `round(px / 0.12)` (`VEL = 0.12` px/ms) and aimed at
  // the middle of its goal window; `tests/test-lesson-solutions.node.js`
  // re-verifies one reference solution per lesson against the real scheduler
  // (Node harness driving `RS.runtime.scheduler` via `iniciarConArbol` /
  // `_procesarFrame`), so a map edit that breaks a lesson fails that test.

  // Single source for Lesson 1's pre-loaded program: main.js's iniciar() reads
  // this for the workspace preload and the `ejemplo` text below quotes it, so
  // the two can never drift. Valid range for this map: 2167-3667 ms.
  RS.lessons.MS_PRECARGA_LECCION_1 = 3000;
  var MS_PRECARGA_LECCION_1 = RS.lessons.MS_PRECARGA_LECCION_1;

  // Lesson 1 keeps its pure-identification teaching goal (no block-building
  // required) but now has a real, run-checkable goal too: a small program is
  // pre-loaded into the workspace by main.js's irALeccion(1) (INICIO ->
  // avanzar -> Delay(MS_PRECARGA_LECCION_1) -> detener()), so the student presses
  // Ejecutar and watches the robot reach the marked meta while reading the
  // identification content. The map is a closed room: the meta covers
  // cols8-12,rows5-9 (x320-520,y200-400), the whole end zone, and col13 (x520)
  // is the back wall. At 3000 ms the robot stops at x=420 — mid-window, with
  // 100px of margin on either side. Overshooting past ~3667 ms (x>500)
  // collides with the back wall, so the wall is genuinely load-bearing.
   var GRID_LECCION_1 = {
    version: 1, cols: 20, rows: 15,
    muros: [
      { col: 0, row: 3 },
      { col: 1, row: 3 },
      { col: 2, row: 3 },
      { col: 0, row: 4 },
      { col: 1, row: 4 },
      { col: 2, row: 4 },
      { col: 3, row: 4 },
      { col: 4, row: 4 },
      { col: 5, row: 4 },
      { col: 6, row: 4 },
      { col: 7, row: 4 },
      { col: 8, row: 4 },
      { col: 9, row: 4 },
      { col: 10, row: 4 },
      { col: 11, row: 4 },
      { col: 12, row: 4 },
      { col: 12, row: 10 },
      { col: 11, row: 10 },
      { col: 10, row: 10 },
      { col: 9, row: 10 },
      { col: 8, row: 10 },
      { col: 7, row: 10 },
      { col: 6, row: 10 },
      { col: 5, row: 10 },
      { col: 4, row: 10 },
      { col: 3, row: 10 },
      { col: 2, row: 10 },
      { col: 1, row: 10 },
      { col: 0, row: 10 },
      { col: 0, row: 11 },
      { col: 0, row: 12 },
      { col: 0, row: 13 },
      { col: 0, row: 14 },
      { col: 1, row: 14 },
      { col: 1, row: 13 },
      { col: 1, row: 12 },
      { col: 1, row: 11 },
      { col: 3, row: 11 },
      { col: 3, row: 12 },
      { col: 3, row: 13 },
      { col: 2, row: 13 },
      { col: 2, row: 14 },
      { col: 2, row: 12 },
      { col: 2, row: 11 },
      { col: 4, row: 13 },
      { col: 5, row: 13 },
      { col: 6, row: 13 },
      { col: 3, row: 14 },
      { col: 4, row: 14 },
      { col: 5, row: 14 },
      { col: 7, row: 13 },
      { col: 8, row: 13 },
      { col: 8, row: 14 },
      { col: 9, row: 14 },
      { col: 10, row: 14 },
      { col: 11, row: 14 },
      { col: 12, row: 14 },
      { col: 7, row: 14 },
      { col: 6, row: 14 },
      { col: 9, row: 13 },
      { col: 10, row: 13 },
      { col: 11, row: 13 },
      { col: 12, row: 13 },
      { col: 13, row: 13 },
      { col: 13, row: 14 },
      { col: 14, row: 14 },
      { col: 15, row: 14 },
      { col: 15, row: 13 },
      { col: 14, row: 13 },
      { col: 16, row: 14 },
      { col: 17, row: 14 },
      { col: 18, row: 14 },
      { col: 19, row: 14 },
      { col: 19, row: 13 },
      { col: 18, row: 13 },
      { col: 18, row: 12 },
      { col: 17, row: 12 },
      { col: 17, row: 13 },
      { col: 16, row: 13 },
      { col: 19, row: 12 },
      { col: 19, row: 11 },
      { col: 18, row: 11 },
      { col: 17, row: 11 },
      { col: 18, row: 10 },
      { col: 18, row: 9 },
      { col: 17, row: 9 },
      { col: 16, row: 10 },
      { col: 16, row: 11 },
      { col: 16, row: 12 },
      { col: 17, row: 8 },
      { col: 16, row: 9 },
      { col: 15, row: 10 },
      { col: 15, row: 11 },
      { col: 15, row: 12 },
      { col: 17, row: 10 },
      { col: 16, row: 8 },
      { col: 15, row: 9 },
      { col: 14, row: 10 },
      { col: 14, row: 11 },
      { col: 13, row: 11 },
      { col: 13, row: 12 },
      { col: 12, row: 12 },
      { col: 14, row: 12 },
      { col: 12, row: 11 },
      { col: 11, row: 11 },
      { col: 11, row: 12 },
      { col: 10, row: 12 },
      { col: 10, row: 11 },
      { col: 9, row: 12 },
      { col: 8, row: 12 },
      { col: 7, row: 12 },
      { col: 6, row: 12 },
      { col: 8, row: 11 },
      { col: 9, row: 11 },
      { col: 5, row: 12 },
      { col: 4, row: 12 },
      { col: 6, row: 11 },
      { col: 7, row: 11 },
      { col: 5, row: 11 },
      { col: 4, row: 11 },
      { col: 13, row: 10 },
      { col: 13, row: 9 },
      { col: 13, row: 8 },
      { col: 13, row: 7 },
      { col: 14, row: 6 },
      { col: 13, row: 6 },
      { col: 13, row: 5 },
      { col: 14, row: 5 },
      { col: 14, row: 4 },
      { col: 14, row: 3 },
      { col: 14, row: 2 },
      { col: 15, row: 3 },
      { col: 15, row: 4 },
      { col: 16, row: 5 },
      { col: 16, row: 6 },
      { col: 16, row: 7 },
      { col: 15, row: 7 },
      { col: 15, row: 5 },
      { col: 15, row: 2 },
      { col: 15, row: 1 },
      { col: 15, row: 0 },
      { col: 16, row: 0 },
      { col: 15, row: 8 },
      { col: 14, row: 7 },
      { col: 14, row: 8 },
      { col: 14, row: 9 },
      { col: 15, row: 6 },
      { col: 16, row: 4 },
      { col: 16, row: 3 },
      { col: 16, row: 2 },
      { col: 18, row: 8 },
      { col: 18, row: 7 },
      { col: 18, row: 6 },
      { col: 18, row: 5 },
      { col: 18, row: 4 },
      { col: 18, row: 3 },
      { col: 17, row: 4 },
      { col: 17, row: 5 },
      { col: 16, row: 1 },
      { col: 17, row: 0 },
      { col: 17, row: 1 },
      { col: 17, row: 2 },
      { col: 17, row: 3 },
      { col: 1, row: 0 },
      { col: 1, row: 1 },
      { col: 0, row: 1 },
      { col: 0, row: 2 },
      { col: 0, row: 0 },
      { col: 2, row: 0 },
      { col: 4, row: 0 },
      { col: 5, row: 0 },
      { col: 6, row: 0 },
      { col: 7, row: 0 },
      { col: 8, row: 0 },
      { col: 6, row: 1 },
      { col: 5, row: 1 },
      { col: 4, row: 1 },
      { col: 3, row: 1 },
      { col: 2, row: 1 },
      { col: 1, row: 2 },
      { col: 2, row: 2 },
      { col: 3, row: 0 },
      { col: 3, row: 2 },
      { col: 3, row: 3 },
      { col: 4, row: 3 },
      { col: 5, row: 3 },
      { col: 6, row: 3 },
      { col: 7, row: 3 },
      { col: 8, row: 3 },
      { col: 4, row: 2 },
      { col: 5, row: 2 },
      { col: 6, row: 2 },
      { col: 7, row: 2 },
      { col: 8, row: 2 },
      { col: 9, row: 2 },
      { col: 10, row: 2 },
      { col: 7, row: 1 },
      { col: 10, row: 3 },
      { col: 11, row: 3 },
      { col: 9, row: 3 },
      { col: 12, row: 3 },
      { col: 13, row: 3 },
      { col: 13, row: 4 },
      { col: 12, row: 2 },
      { col: 11, row: 1 },
      { col: 10, row: 1 },
      { col: 9, row: 1 },
      { col: 13, row: 2 },
      { col: 11, row: 2 },
      { col: 14, row: 1 },
      { col: 12, row: 1 },
      { col: 8, row: 1 },
      { col: 9, row: 0 },
      { col: 10, row: 0 },
      { col: 11, row: 0 },
      { col: 13, row: 0 },
      { col: 14, row: 0 },
      { col: 12, row: 0 },
      { col: 13, row: 1 },
      { col: 18, row: 1 },
      { col: 18, row: 0 },
      { col: 19, row: 0 },
      { col: 19, row: 1 },
      { col: 19, row: 2 },
      { col: 18, row: 2 },
      { col: 19, row: 3 },
      { col: 19, row: 4 },
      { col: 19, row: 5 },
      { col: 19, row: 6 },
      { col: 19, row: 7 },
      { col: 19, row: 8 },
      { col: 19, row: 9 },
      { col: 19, row: 10 },
      { col: 17, row: 7 },
      { col: 17, row: 6 }
    ],
    inicio: { col: 1, row: 7, angulo: 0 },
    meta: { col: 8, row: 5, colSpan: 5, rowSpan: 5 }
  };
  var MAPA_SIN_DESAFIO = RS.gridAdapter.aPixeles(GRID_LECCION_1);

  // Every criterio.evaluar below tests goal-arrival via RS.world.enMeta-
  // equivalent point-in-rect math against ITS OWN `meta` (closed over here,
  // not read from the live RS.world — this keeps criterio.evaluar a pure
  // function of `snapshot` alone, exactly like every other check in this
  // file, and lets tests call it directly with synthetic snapshots without
  // first loading the lesson's map into RS.world). `meta` now comes from
  // `RS.gridAdapter.aPixeles(...)`, but it is still a plain `{x,y,w,h}`
  // pixel rect, so this helper — and every existing call site — is
  // unchanged (design D6).
  function dentroDeMeta(meta, x, y) {
    return x >= meta.x && x <= meta.x + meta.w && y >= meta.y && y <= meta.y + meta.h;
  }

  // True when `y` is within 60px of the lesson's start row. Reads the start
  // pose from the snapshot (not a hard-coded row) so describir() feedback
  // stays correct on maps whose start is not y=300 (e.g. Lesson 5, y=140).
  // Without `snapshot.inicial` it returns false (falls through to the
  // generic message instead of throwing).
  function mismaAlturaQueInicio(snapshot, y) {
    return !!snapshot.inicial && Math.abs(y - snapshot.inicial.y) < 60;
  }

  // Each lesson's grid map is hoisted into a named `GRID_LECCION_N`
  // constant, converted once via `RS.gridAdapter.aPixeles` into the pixel
  // map used both by `mapa` and by `criterio.evaluar` — a single source of
  // truth for the goal rect, so the visual marker and the actual pass/fail
  // zone can never silently drift apart. Every obstacle is a real,
  // collidable AABB; decorative pieces (dressing that never blocks the
  // intended path) are called out per lesson, every other obstacle is
  // load-bearing.
   var GRID_LECCION_2 = {
    version: 1, cols: 20, rows: 15,
    muros: [
      { col: 0, row: 3 },
      { col: 1, row: 3 },
      { col: 2, row: 3 },
      { col: 0, row: 4 },
      { col: 1, row: 4 },
      { col: 2, row: 4 },
      { col: 3, row: 4 },
      { col: 4, row: 4 },
      { col: 5, row: 4 },
      { col: 6, row: 4 },
      { col: 7, row: 4 },
      { col: 8, row: 4 },
      { col: 9, row: 4 },
      { col: 10, row: 4 },
      { col: 11, row: 4 },
      { col: 12, row: 4 },
      { col: 12, row: 10 },
      { col: 11, row: 10 },
      { col: 10, row: 10 },
      { col: 9, row: 10 },
      { col: 8, row: 10 },
      { col: 7, row: 10 },
      { col: 6, row: 10 },
      { col: 5, row: 10 },
      { col: 4, row: 10 },
      { col: 3, row: 10 },
      { col: 2, row: 10 },
      { col: 1, row: 10 },
      { col: 0, row: 10 },
      { col: 0, row: 11 },
      { col: 0, row: 12 },
      { col: 0, row: 13 },
      { col: 0, row: 14 },
      { col: 1, row: 14 },
      { col: 1, row: 13 },
      { col: 1, row: 12 },
      { col: 1, row: 11 },
      { col: 3, row: 11 },
      { col: 3, row: 12 },
      { col: 3, row: 13 },
      { col: 2, row: 13 },
      { col: 2, row: 14 },
      { col: 2, row: 12 },
      { col: 2, row: 11 },
      { col: 4, row: 13 },
      { col: 5, row: 13 },
      { col: 6, row: 13 },
      { col: 3, row: 14 },
      { col: 4, row: 14 },
      { col: 5, row: 14 },
      { col: 7, row: 13 },
      { col: 8, row: 13 },
      { col: 8, row: 14 },
      { col: 9, row: 14 },
      { col: 10, row: 14 },
      { col: 11, row: 14 },
      { col: 12, row: 14 },
      { col: 7, row: 14 },
      { col: 6, row: 14 },
      { col: 9, row: 13 },
      { col: 10, row: 13 },
      { col: 11, row: 13 },
      { col: 12, row: 13 },
      { col: 13, row: 13 },
      { col: 13, row: 14 },
      { col: 14, row: 14 },
      { col: 15, row: 14 },
      { col: 15, row: 13 },
      { col: 14, row: 13 },
      { col: 16, row: 14 },
      { col: 17, row: 14 },
      { col: 18, row: 14 },
      { col: 19, row: 14 },
      { col: 19, row: 13 },
      { col: 18, row: 13 },
      { col: 18, row: 12 },
      { col: 17, row: 12 },
      { col: 17, row: 13 },
      { col: 16, row: 13 },
      { col: 19, row: 12 },
      { col: 19, row: 11 },
      { col: 18, row: 11 },
      { col: 17, row: 11 },
      { col: 18, row: 10 },
      { col: 18, row: 9 },
      { col: 17, row: 9 },
      { col: 16, row: 10 },
      { col: 16, row: 11 },
      { col: 16, row: 12 },
      { col: 17, row: 8 },
      { col: 16, row: 9 },
      { col: 15, row: 10 },
      { col: 15, row: 11 },
      { col: 15, row: 12 },
      { col: 17, row: 10 },
      { col: 16, row: 8 },
      { col: 15, row: 9 },
      { col: 14, row: 10 },
      { col: 14, row: 11 },
      { col: 13, row: 11 },
      { col: 13, row: 12 },
      { col: 12, row: 12 },
      { col: 14, row: 12 },
      { col: 12, row: 11 },
      { col: 11, row: 11 },
      { col: 11, row: 12 },
      { col: 10, row: 12 },
      { col: 10, row: 11 },
      { col: 9, row: 12 },
      { col: 8, row: 12 },
      { col: 7, row: 12 },
      { col: 6, row: 12 },
      { col: 8, row: 11 },
      { col: 9, row: 11 },
      { col: 5, row: 12 },
      { col: 4, row: 12 },
      { col: 6, row: 11 },
      { col: 7, row: 11 },
      { col: 5, row: 11 },
      { col: 4, row: 11 },
      { col: 13, row: 10 },
      { col: 13, row: 9 },
      { col: 13, row: 8 },
      { col: 13, row: 7 },
      { col: 14, row: 6 },
      { col: 13, row: 6 },
      { col: 13, row: 5 },
      { col: 14, row: 5 },
      { col: 14, row: 4 },
      { col: 14, row: 3 },
      { col: 14, row: 2 },
      { col: 15, row: 3 },
      { col: 15, row: 4 },
      { col: 16, row: 5 },
      { col: 16, row: 6 },
      { col: 16, row: 7 },
      { col: 15, row: 7 },
      { col: 15, row: 5 },
      { col: 15, row: 2 },
      { col: 15, row: 1 },
      { col: 15, row: 0 },
      { col: 16, row: 0 },
      { col: 15, row: 8 },
      { col: 14, row: 7 },
      { col: 14, row: 8 },
      { col: 14, row: 9 },
      { col: 15, row: 6 },
      { col: 16, row: 4 },
      { col: 16, row: 3 },
      { col: 16, row: 2 },
      { col: 18, row: 8 },
      { col: 18, row: 7 },
      { col: 18, row: 6 },
      { col: 18, row: 5 },
      { col: 18, row: 4 },
      { col: 18, row: 3 },
      { col: 17, row: 4 },
      { col: 17, row: 5 },
      { col: 16, row: 1 },
      { col: 17, row: 0 },
      { col: 17, row: 1 },
      { col: 17, row: 2 },
      { col: 17, row: 3 },
      { col: 1, row: 0 },
      { col: 1, row: 1 },
      { col: 0, row: 1 },
      { col: 0, row: 2 },
      { col: 0, row: 0 },
      { col: 2, row: 0 },
      { col: 4, row: 0 },
      { col: 5, row: 0 },
      { col: 6, row: 0 },
      { col: 7, row: 0 },
      { col: 8, row: 0 },
      { col: 6, row: 1 },
      { col: 5, row: 1 },
      { col: 4, row: 1 },
      { col: 3, row: 1 },
      { col: 2, row: 1 },
      { col: 1, row: 2 },
      { col: 2, row: 2 },
      { col: 3, row: 0 },
      { col: 3, row: 2 },
      { col: 3, row: 3 },
      { col: 4, row: 3 },
      { col: 5, row: 3 },
      { col: 6, row: 3 },
      { col: 7, row: 3 },
      { col: 8, row: 3 },
      { col: 4, row: 2 },
      { col: 5, row: 2 },
      { col: 6, row: 2 },
      { col: 7, row: 2 },
      { col: 8, row: 2 },
      { col: 9, row: 2 },
      { col: 10, row: 2 },
      { col: 7, row: 1 },
      { col: 10, row: 3 },
      { col: 11, row: 3 },
      { col: 9, row: 3 },
      { col: 12, row: 3 },
      { col: 13, row: 3 },
      { col: 13, row: 4 },
      { col: 12, row: 2 },
      { col: 11, row: 1 },
      { col: 10, row: 1 },
      { col: 9, row: 1 },
      { col: 13, row: 2 },
      { col: 11, row: 2 },
      { col: 14, row: 1 },
      { col: 12, row: 1 },
      { col: 8, row: 1 },
      { col: 9, row: 0 },
      { col: 10, row: 0 },
      { col: 11, row: 0 },
      { col: 13, row: 0 },
      { col: 14, row: 0 },
      { col: 12, row: 0 },
      { col: 13, row: 1 },
      { col: 18, row: 1 },
      { col: 18, row: 0 },
      { col: 19, row: 0 },
      { col: 19, row: 1 },
      { col: 19, row: 2 },
      { col: 18, row: 2 },
      { col: 19, row: 3 },
      { col: 19, row: 4 },
      { col: 19, row: 5 },
      { col: 19, row: 6 },
      { col: 19, row: 7 },
      { col: 19, row: 8 },
      { col: 19, row: 9 },
      { col: 19, row: 10 },
      { col: 17, row: 7 },
      { col: 17, row: 6 }
    ],
    inicio: { col: 1, row: 7, angulo: 0 },
    meta: { col: 8, row: 5, colSpan: 5, rowSpan: 5 }
  };
  var MAPA_LECCION_2 = RS.gridAdapter.aPixeles(GRID_LECCION_2);
  // NOTE: the comment inside the literal below predates the map redesign; the
  // current route needs 4 turns (south, east, north, east) around 2 piers.
   var GRID_LECCION_3 = {
    version: 1, cols: 20, rows: 15,
    muros: [
      { col: 0, row: 6 },
      { col: 1, row: 6 },
      { col: 2, row: 6 },
      { col: 3, row: 6 },
      { col: 4, row: 6 },
      { col: 5, row: 6 },
      { col: 6, row: 6 },
      { col: 7, row: 6 },
      { col: 8, row: 6 },
      { col: 9, row: 6 },
      { col: 10, row: 6 },
      { col: 16, row: 6 },
      { col: 16, row: 7 },
      { col: 16, row: 8 },
      { col: 17, row: 8 },
      { col: 17, row: 9 },
      { col: 17, row: 10 },
      { col: 16, row: 10 },
      { col: 16, row: 11 },
      { col: 16, row: 12 },
      { col: 16, row: 9 },
      { col: 16, row: 13 },
      { col: 16, row: 14 },
      { col: 10, row: 7 },
      { col: 10, row: 8 },
      { col: 10, row: 9 },
      { col: 10, row: 10 },
      { col: 10, row: 11 },
      { col: 10, row: 12 },
      { col: 10, row: 13 },
      { col: 10, row: 14 },
      { col: 9, row: 13 },
      { col: 9, row: 12 },
      { col: 9, row: 14 },
      { col: 9, row: 11 },
      { col: 9, row: 10 },
      { col: 9, row: 9 },
      { col: 9, row: 8 },
      { col: 9, row: 7 },
      { col: 8, row: 7 },
      { col: 7, row: 7 },
      { col: 6, row: 7 },
      { col: 5, row: 7 },
      { col: 4, row: 7 },
      { col: 3, row: 7 },
      { col: 2, row: 7 },
      { col: 1, row: 7 },
      { col: 0, row: 7 },
      { col: 0, row: 8 },
      { col: 1, row: 8 },
      { col: 2, row: 8 },
      { col: 3, row: 8 },
      { col: 4, row: 8 },
      { col: 5, row: 8 },
      { col: 6, row: 8 },
      { col: 7, row: 8 },
      { col: 8, row: 8 },
      { col: 8, row: 9 },
      { col: 7, row: 9 },
      { col: 6, row: 9 },
      { col: 5, row: 9 },
      { col: 4, row: 9 },
      { col: 3, row: 9 },
      { col: 2, row: 9 },
      { col: 1, row: 9 },
      { col: 0, row: 9 },
      { col: 0, row: 10 },
      { col: 1, row: 10 },
      { col: 2, row: 10 },
      { col: 3, row: 10 },
      { col: 4, row: 10 },
      { col: 5, row: 10 },
      { col: 6, row: 10 },
      { col: 7, row: 10 },
      { col: 8, row: 10 },
      { col: 8, row: 11 },
      { col: 7, row: 11 },
      { col: 6, row: 11 },
      { col: 5, row: 11 },
      { col: 4, row: 11 },
      { col: 3, row: 11 },
      { col: 2, row: 11 },
      { col: 1, row: 11 },
      { col: 0, row: 11 },
      { col: 0, row: 12 },
      { col: 1, row: 12 },
      { col: 2, row: 12 },
      { col: 3, row: 12 },
      { col: 4, row: 12 },
      { col: 5, row: 12 },
      { col: 6, row: 12 },
      { col: 7, row: 12 },
      { col: 8, row: 12 },
      { col: 8, row: 13 },
      { col: 7, row: 13 },
      { col: 6, row: 13 },
      { col: 5, row: 13 },
      { col: 4, row: 13 },
      { col: 3, row: 13 },
      { col: 2, row: 13 },
      { col: 1, row: 13 },
      { col: 0, row: 13 },
      { col: 0, row: 14 },
      { col: 1, row: 14 },
      { col: 5, row: 14 },
      { col: 6, row: 14 },
      { col: 7, row: 14 },
      { col: 8, row: 14 },
      { col: 4, row: 14 },
      { col: 3, row: 14 },
      { col: 2, row: 14 },
      { col: 11, row: 13 },
      { col: 12, row: 13 },
      { col: 12, row: 14 },
      { col: 13, row: 13 },
      { col: 14, row: 13 },
      { col: 15, row: 13 },
      { col: 15, row: 14 },
      { col: 14, row: 14 },
      { col: 13, row: 14 },
      { col: 11, row: 14 },
      { col: 17, row: 14 },
      { col: 18, row: 14 },
      { col: 18, row: 13 },
      { col: 17, row: 13 },
      { col: 17, row: 12 },
      { col: 17, row: 11 },
      { col: 17, row: 7 },
      { col: 17, row: 6 },
      { col: 18, row: 6 },
      { col: 19, row: 7 },
      { col: 19, row: 8 },
      { col: 19, row: 9 },
      { col: 19, row: 10 },
      { col: 19, row: 11 },
      { col: 19, row: 12 },
      { col: 19, row: 13 },
      { col: 19, row: 14 },
      { col: 18, row: 12 },
      { col: 18, row: 11 },
      { col: 18, row: 10 },
      { col: 18, row: 9 },
      { col: 18, row: 8 },
      { col: 18, row: 7 },
      { col: 19, row: 6 },
      { col: 19, row: 5 },
      { col: 19, row: 4 },
      { col: 19, row: 3 },
      { col: 18, row: 3 },
      { col: 18, row: 2 },
      { col: 18, row: 1 },
      { col: 18, row: 0 },
      { col: 16, row: 5 },
      { col: 16, row: 4 },
      { col: 16, row: 3 },
      { col: 17, row: 3 },
      { col: 17, row: 2 },
      { col: 17, row: 1 },
      { col: 17, row: 0 },
      { col: 16, row: 0 },
      { col: 16, row: 1 },
      { col: 16, row: 2 },
      { col: 17, row: 5 },
      { col: 18, row: 5 },
      { col: 18, row: 4 },
      { col: 17, row: 4 },
      { col: 19, row: 2 },
      { col: 19, row: 0 },
      { col: 19, row: 1 },
      { col: 15, row: 0 },
      { col: 14, row: 0 },
      { col: 13, row: 0 },
      { col: 12, row: 0 },
      { col: 11, row: 0 },
      { col: 10, row: 0 },
      { col: 9, row: 0 },
      { col: 8, row: 0 },
      { col: 7, row: 0 },
      { col: 6, row: 0 },
      { col: 5, row: 0 },
      { col: 4, row: 0 },
      { col: 3, row: 0 },
      { col: 2, row: 0 },
      { col: 1, row: 0 },
      { col: 0, row: 0 },
      { col: 1, row: 1 },
      { col: 1, row: 2 },
      { col: 1, row: 3 },
      { col: 1, row: 4 },
      { col: 1, row: 5 },
      { col: 0, row: 4 },
      { col: 0, row: 3 },
      { col: 0, row: 2 },
      { col: 0, row: 1 },
      { col: 0, row: 5 }
    ],
    inicio: { col: 3, row: 3, angulo: 0 },
    meta: { col: 11, row: 9, colSpan: 5, rowSpan: 4 }
  };
  var MAPA_LECCION_3 = RS.gridAdapter.aPixeles(GRID_LECCION_3);
  var GRID_LECCION_4 = {
    version: 1, cols: 20, rows: 15,
    muros: [
      { col: 0, row: 6 },
      { col: 1, row: 6 },
      { col: 2, row: 6 },
      { col: 3, row: 6 },
      { col: 4, row: 6 },
      { col: 5, row: 6 },
      { col: 6, row: 6 },
      { col: 7, row: 6 },
      { col: 8, row: 6 },
      { col: 9, row: 6 },
      { col: 10, row: 6 },
      { col: 16, row: 6 },
      { col: 16, row: 7 },
      { col: 16, row: 8 },
      { col: 17, row: 8 },
      { col: 17, row: 9 },
      { col: 17, row: 10 },
      { col: 16, row: 10 },
      { col: 16, row: 11 },
      { col: 16, row: 12 },
      { col: 16, row: 9 },
      { col: 16, row: 13 },
      { col: 16, row: 14 },
      { col: 10, row: 7 },
      { col: 10, row: 8 },
      { col: 10, row: 9 },
      { col: 10, row: 10 },
      { col: 10, row: 11 },
      { col: 10, row: 12 },
      { col: 10, row: 13 },
      { col: 10, row: 14 },
      { col: 9, row: 13 },
      { col: 9, row: 12 },
      { col: 9, row: 14 },
      { col: 9, row: 11 },
      { col: 9, row: 10 },
      { col: 9, row: 9 },
      { col: 9, row: 8 },
      { col: 9, row: 7 },
      { col: 8, row: 7 },
      { col: 7, row: 7 },
      { col: 6, row: 7 },
      { col: 5, row: 7 },
      { col: 4, row: 7 },
      { col: 3, row: 7 },
      { col: 2, row: 7 },
      { col: 1, row: 7 },
      { col: 0, row: 7 },
      { col: 0, row: 8 },
      { col: 1, row: 8 },
      { col: 2, row: 8 },
      { col: 3, row: 8 },
      { col: 4, row: 8 },
      { col: 5, row: 8 },
      { col: 6, row: 8 },
      { col: 7, row: 8 },
      { col: 8, row: 8 },
      { col: 8, row: 9 },
      { col: 7, row: 9 },
      { col: 6, row: 9 },
      { col: 5, row: 9 },
      { col: 4, row: 9 },
      { col: 3, row: 9 },
      { col: 2, row: 9 },
      { col: 1, row: 9 },
      { col: 0, row: 9 },
      { col: 0, row: 10 },
      { col: 1, row: 10 },
      { col: 2, row: 10 },
      { col: 3, row: 10 },
      { col: 4, row: 10 },
      { col: 5, row: 10 },
      { col: 6, row: 10 },
      { col: 7, row: 10 },
      { col: 8, row: 10 },
      { col: 8, row: 11 },
      { col: 7, row: 11 },
      { col: 6, row: 11 },
      { col: 5, row: 11 },
      { col: 4, row: 11 },
      { col: 3, row: 11 },
      { col: 2, row: 11 },
      { col: 1, row: 11 },
      { col: 0, row: 11 },
      { col: 0, row: 12 },
      { col: 1, row: 12 },
      { col: 2, row: 12 },
      { col: 3, row: 12 },
      { col: 4, row: 12 },
      { col: 5, row: 12 },
      { col: 6, row: 12 },
      { col: 7, row: 12 },
      { col: 8, row: 12 },
      { col: 8, row: 13 },
      { col: 7, row: 13 },
      { col: 6, row: 13 },
      { col: 5, row: 13 },
      { col: 4, row: 13 },
      { col: 3, row: 13 },
      { col: 2, row: 13 },
      { col: 1, row: 13 },
      { col: 0, row: 13 },
      { col: 0, row: 14 },
      { col: 1, row: 14 },
      { col: 5, row: 14 },
      { col: 6, row: 14 },
      { col: 7, row: 14 },
      { col: 8, row: 14 },
      { col: 4, row: 14 },
      { col: 3, row: 14 },
      { col: 2, row: 14 },
      { col: 11, row: 13 },
      { col: 12, row: 13 },
      { col: 12, row: 14 },
      { col: 13, row: 13 },
      { col: 14, row: 13 },
      { col: 15, row: 13 },
      { col: 15, row: 14 },
      { col: 14, row: 14 },
      { col: 13, row: 14 },
      { col: 11, row: 14 },
      { col: 17, row: 14 },
      { col: 18, row: 14 },
      { col: 18, row: 13 },
      { col: 17, row: 13 },
      { col: 17, row: 12 },
      { col: 17, row: 11 },
      { col: 17, row: 7 },
      { col: 17, row: 6 },
      { col: 18, row: 6 },
      { col: 19, row: 7 },
      { col: 19, row: 8 },
      { col: 19, row: 9 },
      { col: 19, row: 10 },
      { col: 19, row: 11 },
      { col: 19, row: 12 },
      { col: 19, row: 13 },
      { col: 19, row: 14 },
      { col: 18, row: 12 },
      { col: 18, row: 11 },
      { col: 18, row: 10 },
      { col: 18, row: 9 },
      { col: 18, row: 8 },
      { col: 18, row: 7 },
      { col: 19, row: 6 },
      { col: 19, row: 5 },
      { col: 19, row: 4 },
      { col: 19, row: 3 },
      { col: 18, row: 3 },
      { col: 18, row: 2 },
      { col: 18, row: 1 },
      { col: 18, row: 0 },
      { col: 16, row: 5 },
      { col: 16, row: 4 },
      { col: 16, row: 3 },
      { col: 17, row: 3 },
      { col: 17, row: 2 },
      { col: 17, row: 1 },
      { col: 17, row: 0 },
      { col: 16, row: 0 },
      { col: 16, row: 1 },
      { col: 16, row: 2 },
      { col: 17, row: 5 },
      { col: 18, row: 5 },
      { col: 18, row: 4 },
      { col: 17, row: 4 },
      { col: 19, row: 2 },
      { col: 19, row: 0 },
      { col: 19, row: 1 },
      { col: 15, row: 0 },
      { col: 14, row: 0 },
      { col: 13, row: 0 },
      { col: 12, row: 0 },
      { col: 11, row: 0 },
      { col: 10, row: 0 },
      { col: 9, row: 0 },
      { col: 8, row: 0 },
      { col: 7, row: 0 },
      { col: 6, row: 0 },
      { col: 5, row: 0 },
      { col: 4, row: 0 },
      { col: 3, row: 0 },
      { col: 2, row: 0 },
      { col: 1, row: 0 },
      { col: 0, row: 0 },
      { col: 1, row: 1 },
      { col: 1, row: 2 },
      { col: 1, row: 3 },
      { col: 1, row: 4 },
      { col: 1, row: 5 },
      { col: 0, row: 4 },
      { col: 0, row: 3 },
      { col: 0, row: 2 },
      { col: 0, row: 1 },
      { col: 0, row: 5 }
    ],
    inicio: { col: 3, row: 3, angulo: 0 },
    meta: { col: 11, row: 9, colSpan: 5, rowSpan: 4 }
  };
  var MAPA_LECCION_4 = RS.gridAdapter.aPixeles(GRID_LECCION_4);
  // Start cell (1,3) = pixel (60,140): the robot begins in the upper corridor
  // and must turn south into the shaft above the meta.
  var GRID_LECCION_5 = {
    version: 1, cols: 20, rows: 15,
    muros: [
      { col: 0, row: 0, colSpan: 2 },
      { col: 3, row: 0, colSpan: 17 },
      { col: 18, row: 1, colSpan: 2 },
      { col: 18, row: 2, colSpan: 2 },
      { col: 18, row: 3, colSpan: 2 },
      { col: 18, row: 4, colSpan: 2 },
      { col: 0, row: 10 },
      { col: 0, row: 11 },
      { col: 0, row: 12 },
      { col: 0, row: 13 },
      { col: 0, row: 14, colSpan: 6 },
      { col: 18, row: 10, colSpan: 2 },
      { col: 18, row: 11, colSpan: 2 },
      { col: 18, row: 12, colSpan: 2 },
      { col: 18, row: 13, colSpan: 2 },
      { col: 14, row: 14, colSpan: 6 },
      { col: 7, row: 14 },
      { col: 6, row: 14 },
      { col: 0, row: 1 },
      { col: 0, row: 5 },
      { col: 9, row: 7 },
      { col: 9, row: 8 },
      { col: 9, row: 14 },
      { col: 8, row: 14 },
      { col: 8, row: 8 },
      { col: 8, row: 7 },
      { col: 8, row: 6 },
      { col: 7, row: 6 },
      { col: 6, row: 6 },
      { col: 5, row: 6 },
      { col: 4, row: 6 },
      { col: 3, row: 6 },
      { col: 1, row: 6 },
      { col: 0, row: 6 },
      { col: 0, row: 7 },
      { col: 0, row: 8 },
      { col: 0, row: 9 },
      { col: 1, row: 8 },
      { col: 1, row: 7 },
      { col: 2, row: 7 },
      { col: 2, row: 8 },
      { col: 3, row: 7 },
      { col: 3, row: 8 },
      { col: 4, row: 8 },
      { col: 4, row: 7 },
      { col: 5, row: 7 },
      { col: 5, row: 8 },
      { col: 6, row: 8 },
      { col: 6, row: 7 },
      { col: 7, row: 7 },
      { col: 7, row: 8 },
      { col: 18, row: 7 },
      { col: 18, row: 9 },
      { col: 18, row: 8 },
      { col: 18, row: 6 },
      { col: 18, row: 5 },
      { col: 19, row: 9 },
      { col: 19, row: 8 },
      { col: 19, row: 7 },
      { col: 19, row: 6 },
      { col: 19, row: 5 },
      { col: 10, row: 14 },
      { col: 11, row: 14 },
      { col: 12, row: 14 },
      { col: 13, row: 14 },
      { col: 11, row: 6 },
      { col: 12, row: 6 },
      { col: 10, row: 7 },
      { col: 10, row: 8 },
      { col: 12, row: 7 },
      { col: 11, row: 8 },
      { col: 12, row: 8 },
      { col: 11, row: 7 },
      { col: 0, row: 4 },
      { col: 0, row: 2 },
      { col: 0, row: 3 },
      { col: 9, row: 6 },
      { col: 10, row: 6 },
      { col: 2, row: 0 },
      { col: 2, row: 1 },
      { col: 1, row: 1 },
      { col: 1, row: 2 },
      { col: 1, row: 3 },
      { col: 2, row: 3 },
      { col: 2, row: 4 },
      { col: 2, row: 5 },
      { col: 2, row: 6 },
      { col: 1, row: 5 },
      { col: 1, row: 4 },
      { col: 2, row: 2 },
      { col: 3, row: 1 },
      { col: 3, row: 2 },
      { col: 3, row: 3 },
      { col: 3, row: 4 },
      { col: 3, row: 5 },
      { col: 4, row: 5 },
      { col: 4, row: 2 },
      { col: 4, row: 3 },
      { col: 4, row: 4 },
      { col: 4, row: 1 },
      { col: 4, row: 9 },
      { col: 4, row: 10 },
      { col: 3, row: 10 },
      { col: 3, row: 11 },
      { col: 4, row: 12 },
      { col: 4, row: 13 },
      { col: 3, row: 13 },
      { col: 3, row: 12 },
      { col: 4, row: 11 },
      { col: 3, row: 9 },
      { col: 2, row: 9 },
      { col: 2, row: 10 },
      { col: 2, row: 11 },
      { col: 2, row: 12 },
      { col: 1, row: 9 },
      { col: 1, row: 10 },
      { col: 1, row: 11 },
      { col: 1, row: 12 },
      { col: 2, row: 13 },
      { col: 1, row: 13 }
    ],
    inicio: { col: 7, row: 3, angulo: 0 },
    meta: { col: 5, row: 9, colSpan: 5, rowSpan: 5 }
  };
  var MAPA_LECCION_5 = RS.gridAdapter.aPixeles(GRID_LECCION_5);
  var GRID_LECCION_6 = {
    version: 1, cols: 20, rows: 15,
    muros: [
      { col: 0, row: 0, colSpan: 20, rowSpan: 5 },
      { col: 0, row: 10, colSpan: 20, rowSpan: 5 },
      { col: 19, row: 5 },
      { col: 19, row: 6 },
      { col: 19, row: 7 },
      { col: 18, row: 8 },
      { col: 18, row: 9 },
      { col: 18, row: 7 },
      { col: 18, row: 6 },
      { col: 18, row: 5 },
      { col: 17, row: 5 },
      { col: 17, row: 6 },
      { col: 17, row: 7 },
      { col: 17, row: 8 },
      { col: 19, row: 9 },
      { col: 19, row: 8 },
      { col: 17, row: 9 }
    ],
    inicio: { col: 1, row: 7, angulo: 0 },
    meta: { col: 13, row: 6, colSpan: 3, rowSpan: 3 }
  };
  var MAPA_LECCION_6 = RS.gridAdapter.aPixeles(GRID_LECCION_6);
  // Serpentine: three east-west lanes (3 cells tall each, the minimum corridor
  // width) stacked top to bottom, joined alternately at the east and west ends
  // by a 4-cell gap in the wall between lanes. Start cell (2,2) = pixel
  // (100,100), facing east in the top lane (wide enough for the ejemplo's
  // small square). The meta pocket sits at the east end of the bottom lane.
  // Lane centers are 160px apart, so one lane change is avanzar(1333).
   var GRID_LECCION_7 = {
    version: 1, cols: 20, rows: 15,
    muros: [
      { col: 0, row: 0, colSpan: 20, rowSpan: 5 },
      { col: 0, row: 10, colSpan: 20, rowSpan: 5 },
      { col: 19, row: 5 },
      { col: 19, row: 6 },
      { col: 19, row: 7 },
      { col: 18, row: 8 },
      { col: 18, row: 9 },
      { col: 18, row: 7 },
      { col: 18, row: 6 },
      { col: 18, row: 5 },
      { col: 17, row: 5 },
      { col: 17, row: 6 },
      { col: 17, row: 7 },
      { col: 17, row: 8 },
      { col: 19, row: 9 },
      { col: 19, row: 8 },
      { col: 17, row: 9 }
    ],
    inicio: { col: 1, row: 7, angulo: 0 },
    meta: { col: 13, row: 6, colSpan: 3, rowSpan: 3 }
  };
  var MAPA_LECCION_7 = RS.gridAdapter.aPixeles(GRID_LECCION_7);

  // Start cell (2,2) = pixel (100,100): a single-route ring (upper corridor,
  // right channel down, bottom corridor, left channel up, inner corridor)
  // ending in the meta pocket, which is entered only from the inner corridor.
  var GRID_LECCION_8 = {
    version: 1, cols: 20, rows: 15,
    muros: [
      { col: 0, row: 0, colSpan: 20 },
      { col: 0, row: 12, colSpan: 20, rowSpan: 3 },
      { col: 0, row: 1, rowSpan: 11 },
      { col: 19, row: 1, rowSpan: 11 },
      { col: 1, row: 4, colSpan: 13 },
      { col: 18, row: 4 },
      { col: 1, row: 8 },
      { col: 6, row: 8, colSpan: 13 }
    ],
    inicio: { col: 2, row: 2, angulo: 0 },
    meta: { col: 15, row: 9, colSpan: 3, rowSpan: 3 }
  };
  var MAPA_LECCION_8 = RS.gridAdapter.aPixeles(GRID_LECCION_8);

  RS.lessons.CONTENIDO = [
    {
      id: 1,
      nivel: 'Nivel 1 — Reconocimiento',
      titulo: 'Bloques',
      objetivo: 'En esta lección vas a conocer cómo está organizado el simulador y cómo funcionan los bloques que se arrastran para programar al robot.',
      concepto: 'Una vez iniciada una lección, la pantalla se divide en tres zonas: a la izquierda está la lección con su explicación; en el medio está el espacio de trabajo, donde puedes arrastrar bloques y donde ya hay un conjunto de bloques insertados; a la derecha está el simulador, arriba, con el robot y el desafío o mapa, y abajo el código que se genera para el robot. Los bloques se agrupan por categoría (Inicio, Movimiento, Temporales, Variables, Decisión, Repetición y Sensores) y cada lección desbloquea solo los que necesitas. Un robot combina un sensor (percibe el entorno), un actuador (produce movimiento), un controlador (decide qué hacer: el programa de bloques) y un entorno (el mapa donde se mueve).',
      ejemplo: 'Ya hay un programa armado esperándote: INICIO → avanzar → Delay(' + MS_PRECARGA_LECCION_1 + ') → detener(). No necesitas construir nada todavía — mira el panel Simulador y presiona Ejecutar.',
      bloques: 'Inicio, avanzar, Delay(ms), detener() — ya están armados como referencia; el objetivo de esta lección es identificarlos, no construirlos.',
      comoFunciona: 'El espacio de trabajo muestra el programa armado con bloques: cada bloque se encastra debajo del anterior y se ejecuta en ese orden. El simulador muestra al robot en su mapa: el chasis azul es el cuerpo, las ruedas son el actuador y el sensor frontal mide la distancia a los obstáculos. El código de la parte inferior es la traducción del programa de bloques, y el programa cumple el rol de controlador: decide qué instrucción ejecutar.',
      prueba: 'Presiona Ejecutar y observa cómo el robot avanza y se detiene dentro de la zona de meta marcada en el panel Simulador. Mientras corre, relaciona lo que ves con los roles de la sección «¿Cómo funciona?»: el controlador (el programa) ordena avanzar, el actuador (las ruedas) produce el movimiento y el sensor sigue midiendo distancia aunque el programa no lo consulte todavía.',
      modificacion: 'No aplica en esta lección: no hay programa que modificar todavía.',
      desafio: 'Presiona Ejecutar y confirma que el robot llega y queda detenido dentro de la zona de meta marcada. Después, señala en la pantalla dónde está la lección, dónde se arman los bloques, dónde se ve el simulador y dónde aparece el código.',
      criterioTexto: 'El robot debe llegar y quedar detenido dentro de la zona de meta marcada en el mapa, ejecutando el programa ya armado.',
      pista: 'Pista 1: recuerda que un robot siempre combina percepción (sensor), decisión (controlador) y acción (actuador).',
      competencias: 'C1 — Fundamentos de robótica',
      resultados: 'RA1 — Identificación',
      grid: GRID_LECCION_1,
      mapa: MAPA_SIN_DESAFIO,
      criterio: {
        evaluar: function (snapshot) {
          if (!snapshot || !snapshot.estado) return false;
          return dentroDeMeta(MAPA_SIN_DESAFIO.meta, snapshot.estado.x, snapshot.estado.y);
        }
      }
    },
    {
      id: 2,
      nivel: 'Nivel 2 — Aplicación guiada',
      titulo: 'Secuencia',
      objetivo: 'En esta lección aprenderás qué es un robot y a ordenar tus primeros bloques en una secuencia: iniciar, avanzar, esperar y detener.',
      concepto: 'Un robot es una máquina que percibe su entorno con sensores, decide con un controlador y actúa con motores. Aquí el controlador es tu programa de bloques. En este desafío usas los dos bloques de movimiento iniciales: avanzar, que enciende los motores hacia adelante, y detener(), que los apaga. Una instrucción de movimiento no tiene duración propia: los motores siguen encendidos hasta que otro bloque los cambie. El bloque Delay(ms) hace que el programa espere ese tiempo (en milisegundos) mientras los motores siguen en marcha. Los bloques se ejecutan en orden, de arriba hacia abajo: eso es una secuencia.',
      ejemplo: 'INICIO → avanzar → Delay(2500) → detener()',
      bloques: 'Inicio, avanzar, Delay(ms), detener()',
      comoFunciona: 'El bloque avanzar enciende los motores hacia adelante, pero no espera: el robot sigue avanzando mientras el programa ejecuta Delay(2500), que espera 2500 milisegundos. Después, el bloque detener() apaga los motores. Juntos forman una secuencia: primero se ejecuta avanzar, luego Delay y, solo cuando este termina, se ejecuta detener.',
      prueba: 'Arma la secuencia avanzar → Delay(2500) → detener() en el editor y presiona Ejecutar. Observa cómo se desplaza el robot en el panel Simulador.',
      modificacion: 'Cambia el valor de Delay(2500) por un número distinto y vuelve a ejecutar. Observa cómo cambia la distancia recorrida.',
      desafio: 'Haz que el robot avance durante un tiempo determinado y quede detenido dentro de la zona marcada al fondo de la sala, sin chocar contra la pared del fondo.',
      criterioTexto: 'El robot debe avanzar y quedar detenido dentro de la zona de meta marcada en el mapa (la zona al fondo de la sala), sin colisionar contra la pared del fondo.',
      pista: 'Pista 1: recuerda que avanzar enciende los motores y Delay(ms) decide cuánto tiempo siguen encendidos; a mayor ms, mayor distancia. Pista 2: si el tiempo es muy corto, el robot no llega a la zona marcada; si es muy largo, choca contra la pared del fondo.',
      competencias: 'C2 — Movimiento y control',
      resultados: 'RA2 — Movimiento',
      // Geometry/verification: see MAPA_LECCION_2 above.
      grid: GRID_LECCION_2,
      mapa: MAPA_LECCION_2,
      criterio: {
        evaluar: function (snapshot) {
          if (!snapshot || !snapshot.estado) return false;
          return dentroDeMeta(MAPA_LECCION_2.meta, snapshot.estado.x, snapshot.estado.y);
        }
      }
    },
    {
      id: 3,
      nivel: 'Nivel 2 — Aplicación guiada',
      titulo: 'Secuencia II',
      objetivo: 'En esta lección aprenderás a combinar giros y avances en una secuencia más larga, para llevar al robot por un recorrido con forma de L.',
      concepto: 'Se añaden los bloques derecha e izquierda (y retroceder). Igual que avanzar, trabajan junto con Delay: encienden los motores y estos siguen en marcha mientras el programa espera, así que el tiempo del Delay decide cuánto gira el robot (500 ms equivalen a un giro de 90°, un ángulo recto). El bloque detener() apaga todos los motores, por eso conviene ponerlo entre un tramo y el siguiente. El mapa tiene forma de L: hay una curva que obliga a redireccionar al robot. Cambiar el orden de los bloques cambia el recorrido.',
      ejemplo: 'INICIO → avanzar → Delay(3000) → detener() → derecha → Delay(500) → detener() → avanzar → Delay(2500) → detener()',
      bloques: 'Inicio, avanzar, retroceder, derecha, izquierda, Delay(ms), detener()',
      comoFunciona: 'Cada bloque se ejecuta en orden. Primero avanzar con Delay(3000) lleva al robot hacia el este por el tramo recto y detener() apaga los motores. Luego derecha con Delay(500) lo gira 90° sobre su lugar hacia el sur y el siguiente detener() frena el giro. Por último, avanzar con Delay(2500) lo desplaza en la nueva dirección hasta la meta y detener() lo deja quieto.',
      prueba: 'Arma la secuencia avanzar → Delay(3000) → detener() → derecha → Delay(500) → detener() → avanzar → Delay(2500) → detener() en el editor y presiona Ejecutar. Observa el recorrido en forma de "L": el robot avanza hacia el este, gira a la derecha en la curva y baja hacia el sur.',
      modificacion: 'Cambia el Delay(500) del giro por Delay(250) y vuelve a ejecutar. Observa que el robot gira solo la mitad de un ángulo recto y su recorrido ya no sigue la curva del mapa: el tiempo de giro decide el ángulo.',
      desafio: 'Arma una secuencia con el orden Iniciar → Avanzar → Delay → Detener → Derecha → Delay → Detener → Avanzar → Delay → Detener que lleve al robot por la curva del mapa en L hasta la zona de meta marcada.',
      criterioTexto: 'El robot debe avanzar por el tramo recto, girar a la derecha en la curva y quedar detenido dentro de la zona de meta marcada, sin colisionar.',
      pista: 'Pista 1: recuerda que las instrucciones se ejecutan en el orden exacto en que las colocaste, una tras otra. Pista 2: si avanzas demasiado antes de girar, el robot chocará contra la pared; el giro tiene que ocurrir antes de llegar a ella. Pista 3: 500 ms de giro equivalen a un ángulo recto. Pista 4: detener() apaga todos los motores; úsalo entre un tramo y el siguiente.',
      competencias: 'C3 — Secuenciación de instrucciones',
      resultados: 'RA3 — Secuencias',
      // Geometry/verification: see MAPA_LECCION_3 above.
      grid: GRID_LECCION_3,
      mapa: MAPA_LECCION_3,
      criterio: {
        evaluar: function (snapshot) {
          if (!snapshot || !snapshot.estado) return false;
          return dentroDeMeta(MAPA_LECCION_3.meta, snapshot.estado.x, snapshot.estado.y);
        },
        describir: function (snapshot, ok) {
          if (!snapshot || !snapshot.estado) return null;
          var x = Math.round(snapshot.estado.x);
          var y = Math.round(snapshot.estado.y);
          if (ok) {
            return 'El robot rodeó los pilares y terminó en x=' + x + 'px, y=' + y + 'px, dentro de la zona de meta.';
          }
          if (mismaAlturaQueInicio(snapshot, y)) {
            return 'El robot terminó casi a la misma altura que al inicio (y=' + y + 'px): la secuencia no llegó a girar a tiempo.';
          }
          return 'El robot terminó en x=' + x + 'px, y=' + y + 'px, fuera de la zona de meta.';
        }
      }
    },
    {
      id: 4,
      nivel: 'Nivel 2 — Aplicación guiada',
      titulo: 'Variables',
      objetivo: 'En esta lección aprenderás a guardar un valor en una variable y a usarla dentro de un bloque, para que el giro del robot dependa de un único número que puedes cambiar en un solo lugar.',
      concepto: 'Una variable es un nombre que guarda un valor mientras el programa se ejecuta. Se declara una sola vez indicando su tipo: "int" guarda números enteros y "bool" guarda verdadero o falso. Como el tiempo de giro es siempre el mismo, conviene guardarlo: crear una variable giro con valor 500 permite escribir derecha → Delay(giro) y el robot dobla en ángulo recto; si más adelante ese valor cambia, solo hay que modificarlo en la declaración. La variable se declara al principio del programa, antes de usarla.',
      ejemplo: 'INICIO → declarar int giro = 500 → avanzar → Delay(3000) → detener() → derecha → Delay(giro) → detener() → avanzar → Delay(2500) → detener()',
      bloques: 'Inicio, declarar (int / bool), valor de variable, avanzar, retroceder, derecha, izquierda, Delay(ms), detener()',
      comoFunciona: 'El bloque "declarar int giro = 500" crea la variable con valor 500 al comienzo del programa. Más adelante, el bloque de valor de variable giro se coloca dentro del Delay del giro: en vez de un número fijo, el Delay lee lo que guarda la variable. El resto funciona igual que en la lección anterior: avanzar, girar con derecha y volver a avanzar, con detener() entre un tramo y el siguiente.',
      prueba: 'Arma el ejemplo (declarar int giro = 500 → avanzar → Delay(3000) → detener() → derecha → Delay(giro) → detener() → avanzar → Delay(2500) → detener()) y presiona Ejecutar. Observa que el robot sigue el mismo recorrido en L de la lección anterior, pero ahora el giro depende de la variable.',
      modificacion: 'Cambia el valor de la declaración de 500 a 250 y vuelve a ejecutar sin tocar el resto del programa. Observa que el giro cambia, porque el Delay del giro lee el nuevo valor de la variable.',
      desafio: 'Resuelve de nuevo el recorrido en L de la lección anterior, pero declarando una variable giro con valor 500 y usándola como tiempo del Delay en el bloque derecha.',
      criterioTexto: 'El robot debe llegar y quedar detenido dentro de la zona de meta marcada, usando una variable para el tiempo de giro.',
      pista: 'Pista 1: declara la variable antes del primer movimiento, no dentro de un tramo. Pista 2: arrastra el bloque de valor de variable al hueco del Delay del giro, en lugar de escribir un número. Pista 3: 500 ms de giro equivalen a un ángulo recto. Pista 4: el nombre que eliges en la declaración debe ser el mismo que usas al leer la variable.',
      competencias: 'C4 — Variables y estado del programa',
      resultados: 'RA4 — Uso de variables',
      // Geometry/verification: see MAPA_LECCION_4 above.
      grid: GRID_LECCION_4,
      mapa: MAPA_LECCION_4,
      criterio: {
        evaluar: function (snapshot) {
          if (!snapshot || !snapshot.estado || !snapshot.metricas) return false;
          if (snapshot.metricas.evalsSensor < 1) return false;
          return dentroDeMeta(MAPA_LECCION_4.meta, snapshot.estado.x, snapshot.estado.y);
        },
        describir: function (snapshot, ok) {
          if (!snapshot || !snapshot.estado) return null;
          var x = Math.round(snapshot.estado.x);
          var evals = snapshot.metricas ? snapshot.metricas.evalsSensor : 0;
          if (ok) {
            return 'El robot consultó su sensor y se detuvo dentro de la zona de meta, cerca del muro del fondo (x=' + x + 'px).';
          }
          if (!evals) {
            return 'El robot terminó su ejecución sin haber consultado nunca su sensor de distancia.';
          }
          return 'El robot terminó en x=' + x + 'px, fuera de la zona de meta.';
        }
      }
    },
    {
      id: 5,
      nivel: 'Nivel 2 — Aplicación guiada',
      titulo: 'Iteración',
      objetivo: 'En esta lección aprenderás a usar el bloque "repetir N veces" para que el robot repita una secuencia completa sin que tengas que copiar los bloques una y otra vez.',
      concepto: 'Una iteración repite un conjunto de bloques. El bloque "repetir N veces" ejecuta su contenido exactamente N veces, una pasada tras otra. Cuando un recorrido tiene la misma forma varias veces (por ejemplo, una doble L), en vez de duplicar la secuencia de la lección anterior la rodeas con un bloque de repetición: todo lo que queda dentro del bloque se repite. Las variables declaradas antes del bucle, como giro, se pueden seguir usando dentro de él.',
      ejemplo: 'INICIO → declarar int giro = 500 → repetir 2 veces { avanzar → Delay(3000) → detener() → derecha → Delay(giro) → detener() → avanzar → Delay(2500) → detener() } (los Delay se ajustan a la medida de cada tramo del mapa).',
      bloques: 'Inicio, declarar (int), valor de variable, repetir N veces, avanzar, derecha, izquierda, retroceder, Delay(ms), detener()',
      comoFunciona: 'El bloque "repetir 2 veces" contiene la misma secuencia de la lección anterior: avanzar, esperar, detener, girar con la variable giro, y avanzar de nuevo. En la primera pasada el robot recorre una L; al terminar, el bucle vuelve al principio de su contenido y ejecuta la secuencia una segunda vez, completando la doble L. Lo que está fuera del bloque, como la declaración de giro, se ejecuta una sola vez.',
      prueba: 'Arma la secuencia de la lección anterior, rodéala con un bloque "repetir 2 veces" y presiona Ejecutar. Observa que el robot repite el mismo patrón de avance y giro dos veces seguidas, sin que hayas duplicado los bloques.',
      modificacion: 'Cambia el 2 del bloque de repetición por 1 y vuelve a ejecutar. El robot recorre una sola L y no llega a la meta: la cantidad de repeticiones decide cuánto recorrido se completa.',
      desafio: 'Programa al robot para que recorra el mapa con forma de doble L, rodeando con un bloque "repetir 2 veces" la secuencia de la lección anterior (incluida la variable giro).',
      criterioTexto: 'El robot debe recorrer la doble L y quedar detenido dentro de la zona de meta marcada, sin colisionar, usando un bloque de repetición para el mismo código dos veces.',
      pista: 'Pista 1: recuerda que todo lo que está dentro de "repetir N veces" se ejecuta N veces, y lo que está fuera se ejecuta una sola vez. Pista 2: declara la variable giro antes del bucle, no dentro. Pista 3: cada pasada debe dejar al robot listo para repetir el mismo patrón, así que termina cada una con detener(). Pista 4: si la segunda pasada choca contra una pared, revisa los Delay de cada tramo.',
      competencias: 'C5 — Iteración',
      resultados: 'RA5 — Repetición de secuencias',
      // Geometry/verification: see MAPA_LECCION_5 above.
      grid: GRID_LECCION_5,
      mapa: MAPA_LECCION_5,
      criterio: {
        evaluar: function (snapshot) {
          if (!snapshot || !snapshot.estado || !snapshot.metricas) return false;
          if (snapshot.metricas.evalsSensor < 1) return false;
          return dentroDeMeta(MAPA_LECCION_5.meta, snapshot.estado.x, snapshot.estado.y);
        },
        describir: function (snapshot, ok) {
          if (!snapshot || !snapshot.estado) return null;
          var x = Math.round(snapshot.estado.x);
          var y = Math.round(snapshot.estado.y);
          var evals = snapshot.metricas ? snapshot.metricas.evalsSensor : 0;
          if (ok) {
            return 'El robot consultó su sensor, tomó la decisión correcta y terminó en x=' + x + 'px, y=' + y + 'px, dentro de la zona de meta.';
          }
          if (!evals) {
            return 'El robot terminó su ejecución sin haber consultado nunca su sensor, por lo que nunca tomó una decisión basada en lo que percibe.';
          }
          if (mismaAlturaQueInicio(snapshot, y)) {
            return 'El robot consultó su sensor pero terminó casi a la misma altura que al inicio (y=' + y + 'px): la rama tomada no cambió su dirección de avance.';
          }
          return 'El robot terminó en x=' + x + 'px, y=' + y + 'px, fuera de la zona de meta.';
        }
      }
    },
    {
      id: 6,
      nivel: 'Nivel 3 — Autonomía',
      titulo: 'Condición y sensores',
      objetivo: 'En esta lección aprenderás qué es un sensor y a usar los bloques "mientras", "si / si no" y hayObstaculo() para que el robot decida por sí mismo cuándo detenerse.',
      concepto: 'Un sensor es un componente que percibe una condición del entorno; el sensor del robot detecta si hay un obstáculo adelante, y el bloque hayObstaculo() entrega esa lectura como verdadero o falso. Un condicional "si / si no" elige siempre una de dos ramas según esa lectura. El bloque "mientras" repite su contenido mientras su condición sea verdadera; con la condición verdadero, el bucle es infinito. La combinación es: un "mientras verdadero" que en cada pasada consulta el sensor. Cuando el robot detecta un obstáculo, detiene los motores y ejecuta Salir, que abandona el bucle: Salir oficia de "break" del mientras.',
      ejemplo: 'INICIO → mientras verdadero { si hayObstaculo() { detener() → Salir } si no { avanzar } }',
      bloques: 'Inicio, mientras, si / si no, hayObstaculo(), Salir, avanzar, detener()',
      comoFunciona: 'En cada pasada del "mientras verdadero", el bloque "si / si no" consulta hayObstaculo(). Si no hay obstáculo, se ejecuta la rama "si no" y el robot avanza. Cuando el sensor detecta el obstáculo, se ejecuta la primera rama: detener() apaga los motores y Salir termina el bucle. Como la condición del "mientras" nunca deja de ser verdadera, Salir es la única forma de terminar el programa.',
      prueba: 'Arma "mientras verdadero { si hayObstaculo() { detener() → Salir } si no { avanzar } }" en el editor y presiona Ejecutar. Observa que el robot avanza solo y se detiene cuando el sensor detecta el obstáculo, sin que hayas calculado ningún tiempo.',
      modificacion: 'Quita el bloque Salir de la rama "si" y ejecuta de nuevo. El robot se detiene frente al obstáculo, pero el bucle sigue consultando el sensor sin terminar: sin Salir, el programa no finaliza.',
      desafio: 'Programa al robot para que avance por el pasillo recto y se detenga solo al detectar el obstáculo, usando "mientras verdadero" y un "si / si no" con el sensor, sin ningún Delay.',
      criterioTexto: 'El robot debe quedar detenido dentro de la zona de meta marcada, cerca del obstáculo del fondo, habiendo consultado el sensor al menos dos veces.',
      pista: 'Pista 1: recuerda que "si / si no" siempre ejecuta una de sus dos ramas en cada pasada. Pista 2: la rama del sensor (hay obstáculo) debe detener al robot y salir del bucle; la otra rama debe avanzar. Pista 3: sin Salir, el "mientras verdadero" nunca termina. Pista 4: si el robot choca contra el obstáculo, revisa que la condición del "si" sea hayObstaculo().',
      competencias: 'C6 — Sensores y decisión',
      resultados: 'RA6 — Condicionales y sensores',
      // Geometry/verification: see MAPA_LECCION_6 above.
      grid: GRID_LECCION_6,
      mapa: MAPA_LECCION_6,
      criterio: {
        evaluar: function (snapshot) {
          if (!snapshot || !snapshot.estado || !snapshot.metricas) return false;
          var m = snapshot.metricas;
          if (m.evalsSensor < 2) return false;
          return dentroDeMeta(MAPA_LECCION_6.meta, snapshot.estado.x, snapshot.estado.y);
        },
        describir: function (snapshot, ok) {
          if (!snapshot || !snapshot.estado) return null;
          var x = Math.round(snapshot.estado.x);
          var m = snapshot.metricas || { evalsSensor: 0 };
          if (ok) {
            return 'El robot repitió el paso hasta detectar el muro con su sensor y se detuvo en x=' + x + 'px, dentro de la zona de meta.';
          }
          if (m.evalsSensor < 2) {
            return 'El robot terminó su ejecución habiendo consultado el sensor menos de dos veces: el bucle no llegó a repetirse lo suficiente.';
          }
          return 'El robot no se detuvo dentro de la zona de meta (x=' + x + 'px).';
        }
      }
    },
    {
      id: 7,
      nivel: 'Nivel 3 — Autonomía',
      titulo: 'Condición II',
      objetivo: 'En esta lección aprenderás a usar el bloque noHayObstaculo() como condición de un "mientras", para escribir el mismo comportamiento con menos bloques.',
      concepto: 'El bloque noHayObstaculo() es el opuesto de hayObstaculo(): es verdadero cuando no hay nada adelante. Si se usa como condición de un "mientras", el bucle se repite mientras el camino esté libre y termina por sí solo cuando el sensor detecta un obstáculo, sin necesidad de un "si" ni de Salir. Después del bucle, el programa continúa con el siguiente bloque.',
      ejemplo: 'INICIO → mientras noHayObstaculo() { avanzar → Delay(100) } → detener()',
      bloques: 'Inicio, mientras, noHayObstaculo(), avanzar, Delay(ms), detener()',
      comoFunciona: 'Antes de cada pasada, el bloque "mientras" consulta noHayObstaculo(). Mientras sea verdadero, ejecuta avanzar → Delay(100) y vuelve a preguntar; es decir, mientras no haya un obstáculo adelante, el robot sigue avanzando. En cuanto el sensor detecta uno, la condición pasa a falso, el bucle termina y detener() apaga los motores.',
      prueba: 'Arma "mientras noHayObstaculo() { avanzar → Delay(100) }" seguido de detener() y presiona Ejecutar. Observa que el robot avanza en pasos cortos y se detiene solo frente al obstáculo.',
      modificacion: 'Quita el bloque Delay(100) del cuerpo del bucle y vuelve a ejecutar. Compara el comportamiento: sin esperar, el robot consulta el sensor en cada pasada y avanza igual, solo que el programa revisa la condición con más frecuencia.',
      desafio: 'Programa al robot para que avance por el pasillo recto y se detenga frente al obstáculo usando un único "mientras noHayObstaculo()" y un detener() final.',
      criterioTexto: 'El robot debe quedar detenido dentro de la zona de meta marcada, cerca del obstáculo del fondo, habiendo consultado el sensor al menos una vez.',
      pista: 'Pista 1: recuerda que "mientras" consulta la condición antes de cada pasada. Pista 2: usa pasos pequeños, como avanzar → Delay(100), para no pasarte del punto donde el sensor detecta el obstáculo. Pista 3: el detener() va después del bucle, no dentro. Pista 4: si el robot nunca se detiene, revisa que la condición sea noHayObstaculo() y no hayObstaculo().',
      competencias: 'C7 — Repetición condicionada',
      resultados: 'RA7 — Bucles con condición de sensor',
      // Geometry/verification: see MAPA_LECCION_7 above.
      grid: GRID_LECCION_7,
      mapa: MAPA_LECCION_7,
      criterio: {
        evaluar: function (snapshot) {
          if (!snapshot || !snapshot.estado || !snapshot.metricas) return false;
          var m = snapshot.metricas;
          if (m.evalsSensor < 1) return false;
          return dentroDeMeta(MAPA_LECCION_7.meta, snapshot.estado.x, snapshot.estado.y);
        },
        describir: function (snapshot, ok) {
          if (!snapshot || !snapshot.estado) return null;
          var x = Math.round(snapshot.estado.x);
          var y = Math.round(snapshot.estado.y);
          var m = snapshot.metricas || { evalsSensor: 0 };
          if (ok) {
            return 'El robot avanzó mientras no había obstáculo y se detuvo dentro de la zona de meta (x=' + x + 'px, y=' + y + 'px).';
          }
          if (!m.evalsSensor) {
            return 'El robot terminó su ejecución sin haber consultado nunca su sensor para detectar el obstáculo.';
          }
          return 'El robot no llegó a la zona de meta: se detuvo en x=' + x + 'px, y=' + y + 'px.';
        }
      }
    },
    {
      id: 8,
      nivel: 'Nivel 3 — Autonomía',
      titulo: 'Integración',
      objetivo: 'En esta lección vas a combinar todo lo aprendido — secuencias, variables, repetición, sensores y condiciones — para programar al robot a lo largo de un recorrido con forma de espiral.',
      concepto: 'Un programa completo casi nunca usa una sola herramienta: combina secuencias de pasos, variables para valores que se repiten (como el tiempo de giro), repeticiones para patrones que se repiten y condiciones con sensores para reaccionar a lo que el robot percibe. No existe una única forma correcta de resolver un mismo problema: dos programas distintos pueden lograr el mismo resultado si ambos hacen que el robot recorra el camino sin chocar.',
      ejemplo: 'INICIO → declarar int giro = 500 → mientras noHayObstaculo() { avanzar → Delay(100) } → detener() → derecha → Delay(giro) → detener() (primer tramo y primer giro de la espiral; a partir de ahí, tú decides cómo continuar).',
      bloques: 'Inicio, avanzar, retroceder, derecha, izquierda, Delay(ms), detener(), declarar (int / bool), valor de variable, repetir N veces, mientras, si / si no, hayObstaculo(), noHayObstaculo(), Salir',
      comoFunciona: 'Cada herramienta cumple su rol: la secuencia ordena los pasos, la variable guarda el tiempo de giro para usarlo en cada esquina, "repetir N veces" evita copiar el mismo patrón y los bloques con sensor hacen que el robot se acerque a cada pared sin que calcules distancias de antemano. Combinadas, permiten recorrer una espiral, donde cada tramo es más corto que el anterior.',
      prueba: 'Arma el ejemplo (declarar int giro = 500 → mientras noHayObstaculo() { avanzar → Delay(100) } → detener() → derecha → Delay(giro) → detener()) y presiona Ejecutar. Observa que el robot recorre el primer tramo, se detiene frente a la pared y gira, listo para que agregues el resto del recorrido.',
      modificacion: 'A partir del ejemplo, agrega otro "mientras noHayObstaculo()" y otro giro para recorrer el siguiente tramo, y sigue completando el recorrido paso a paso hasta que el robot llegue a la zona de meta.',
      desafio: 'Programa al robot para que recorra la espiral completa y llegue a la zona de meta, usando variables, repetición y sensores para decidir dónde girar en cada esquina, sin chocar en ningún momento.',
      criterioTexto: 'El robot debe recorrer el recorrido completo y quedar detenido dentro de la zona de meta marcada, habiendo consultado el sensor al menos una vez durante la ejecución, y sin haber chocado. No existe un único programa correcto: cualquier combinación de bloques que lo recorra sin chocar es válida.',
      pista: 'Pista 1: piensa el desafío como varios tramos encadenados: cada tramo termina frente a una pared, y allí hay que girar. Pista 2: usa el sensor para acercarte a cada pared, en vez de adivinar una distancia fija. Pista 3: una espiral gira siempre hacia el mismo lado, así que cada esquina se resuelve con el mismo giro y el mismo valor de la variable giro; un bloque "repetir N veces" evita copiar el patrón. Pista 4: los pasillos son angostos: si el robot se desvía o toca una pared, la ejecución se detiene.',
      competencias: 'C8 — Integración de secuencias, variables, repetición y sensores',
      resultados: 'RA8 — Programa autónomo completo',
      // Geometry/verification: see MAPA_LECCION_8 above.
      grid: GRID_LECCION_8,
      mapa: MAPA_LECCION_8,
      criterio: {
        evaluar: function (snapshot) {
          if (!snapshot || !snapshot.estado || !snapshot.metricas) return false;
          return dentroDeMeta(MAPA_LECCION_8.meta, snapshot.estado.x, snapshot.estado.y);
        },
        describir: function (snapshot, ok) {
          if (!snapshot || !snapshot.estado) return null;
          var x = Math.round(snapshot.estado.x);
          if (ok) {
            return 'El robot recorrió el circuito y llegó a la zona de meta (x=' + x + 'px) sin chocar.';
          }
          return 'El robot no completó el circuito: se detuvo en x=' + x + 'px, fuera de la zona de meta.';
        }
      }
    }
  ];
})(typeof window !== 'undefined' ? window : this);
